server:
  port: 8091

spring:
  datasource:
    username: 'postgres'
    password: '12345'
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/socialMediaUser'
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true