server:
  port: 8888

spring:
  zipkin:
    enabled: true
    base-url: htt://localhost:9411
    service:
      name: config-service
  application:
    name:config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/servicesyml